
Login_txt = "Login 🖥"
dars_jadvali_txt = "Dars jadvali 📆"
admin = "© Dasturchi"
talaba_info_txt = "Mening malumotlarim 👨‍🎓"
davomad_txt = "Davomat 📈"
baholar_txt = "✔️ Baholar"
admin_secret_txt = "tsue_admin"
admin_shikoyat_list_txt = "Taklif va shikoyatlarni ko'rish"
admin_back_menu_txt = "Back to main 🔙"